# Generated by Django 5.2.16 on 2026-07-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
