# Generated by Django 5.2.16 on 2026-07-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_organization_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="established_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="license_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="pan_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="registration_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
