# Generated by Django 5.2.16 on 2026-07-20 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockin'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
