# Generated by Django 5.2.16 on 2026-07-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockout',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
