# Generated by Django 5.2.16 on 2026-07-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_qunatity_stockout_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode used for POS scanning', max_length=50, null=True, unique=True),
        ),
    ]
