# Generated by Django 5.2.16 on 2026-07-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_minimum_stock_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
