# Generated by Django 5.2.16 on 2026-07-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
