# Generated by Django 5.2.16 on 2026-07-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_stockin_batch_number_alter_stockin_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
    ]
