# Generated by Django 5.2.16 on 2026-07-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
