# Generated by Django 5.2.16 on 2026-07-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('FONEPAY', 'FonePay'), ('ESEWA', 'Esewa'), ('BANK TRANSFER', 'Bank Transfer')], default='CASH', max_length=20),
        ),
    ]
