# Generated by Django 5.2.16 on 2026-07-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='expiry_date',
        ),
    ]
